[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "blog-builder"
version = "0.1.0"
dependencies = [
    "fastapi",
    "gitpython",
    "uvicorn",
]

[tool.setuptools]
py-modules = ["main"]

[project.scripts]
blog-builder = "main:main"
